### ISSUE TITLE
Issue calculating H index with multiple_sounds function

### ISSUE THREAD

**Issue by ali-fairbrass** [ljvillanueva/soundecology#2]
With the following code:

multiple_sounds(directory=wavfiledirectory, resultfile=csvfile,
                soundindex="H", no_cores="max")

Where wavfiledirectory and csvfile are defined to filepaths, I receive the following error message before RStudio crashes:

Running the function H() on 10 files using 8 cores

Error in UseMethod("depth") :
no applicable method for 'depth' applied to an object of class "NULL"
Error in UseMethod("depth") :
no applicable method for 'depth' applied to an object of class "NULL"
Error in grid.Call.graphics(L_setviewport, vp, TRUE) :
VECTOR_ELT() can only be applied to a 'list', not a 'NULL'

An empty output csv file with the header was created.

When testing the H function on a single file via the seewave package with the following code:

H(wavfilepath, f=24000)

I receive the following error message:

Error in seq.default(1, n - wl, wl - (ovlp \* wl/100)) : 
  wrong sign in 'by' argument

Have asked about this issue on seewave googlegroup: https://groups.google.com/forum/#!topic/seewave/zGNeSMG3IVo

Apparently this is due to the wl argument not being defined properly. So may be the issue with the multiple_sounds function.
1. Do you know how to find the correct wl for your sound file?
2. Could the seewave error message be produced by soundecology when using the H index in multiple_sounds?

**Comment by ali-fairbrass** [comment]
The issue of calculating H for a single file has been resolved: https://groups.google.com/forum/#!topic/seewave/zGNeSMG3IVo

I have tried hard coding the readWave arguments that were recommended into the function but without success.

Is there any way I can use the multiple_sounds function and define the arguments for the readWave function?

Thanks

**Comment by villanueval** [comment]
I've uploaded version 1.2 to CRAN, which will let you add the arguments:
- from
- to
- units

to readWave().
